server:
  port: 8080

#注册到注册中心的名称
spring:
  application:
    name: member-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/,http://localhost:9100/eureka/
    register-with-eureka: true
    fetch-registry: true