

###会员服务的端口号
server:
  port: 8502
###服务别名----服务注册到注册中心名称
spring:
  application:
    name: consul-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: order-service
        heartbeat:
          enabled: true
          ttl-value: 30



